export const SHOW_ADV = "SHOW_ADV";



export const TOGGLE_SETTINGS = "TOGGLE_SETTINGS";
export const TOGGLE_SOUNDS = "TOGGLE_SOUNDS";


export const CHOOSE_GAME = "CHOOSE_GAME";
export const CHOOSE_DIFFICULT = "CHOOSE_DIFFICULT";
export const CHOOSE_LEVEL = "CHOOSE_LEVEL";


//Покупки за монеты
export const SUBTRACT_MONEY = "SUBTRACT_MONEY";
export const ADD_MONEY = "ADD_MONEY";

export const BUY_GAME = "BUY_GAME";
export const BUY_EXPERT_DIFF = "BUY_EXPERT_DIFF";
export const SKIP_LEVEL = "SKIP_LEVEL";
//Уровень
export const ADD_EXP = "ADD_EXP";
export const GET_NEW_LEVEL = "GET_NEW_LEVEL";

export const ADD_DONE_LEVEL = "ADD_DONE_LEVEL";

//Данные
export const CHANGE_PROGRESS_FROM_PLAYER_DATA = "CHANGE_PROGRESS_FROM_PLAYER_DATA";
export const CHANGE_LEVEL_FROM_PLAYER_DATA = "CHANGE_LEVEL_FROM_PLAYER_DATA";
export const CHANGE_EXP_FROM_PLAYER_DATA = "CHANGE_EXP_FROM_PLAYER_DATA";
export const CHANGE_MONEY_FROM_PLAYER_DATA = "CHANGE_MONEY_FROM_PLAYER_DATA";
//Рандомная игра
export const CHANGE_RAND_GAME = "CHANGE_RAND_GAME";